name: Windows Basement Build

on: [push]

env:
  CMAKE_Fortran_COMPILER: "/c/msys64/mingw64/bin/x86_64-w64-mingw32-gfortran.exe"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BUILD_TYPE: Debug
  Python_REQUIRED_VERSION: 3.8

jobs:
  windows_release:
    runs-on: windows-2019
    continue-on-error: ${{ matrix.allow_failure }}
    strategy:
      # fail-fast: Default is true, switch to false to allow one platform to fail and still run others
      fail-fast: false
      matrix:
        arch: [x64]
        include:
        - arch: x64
          allow_failure: false
          vs-generator: x64
          package-arch: x86_64

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ env.Python_REQUIRED_VERSION }}
      uses: actions/setup-python@v2
      id: setup-python
      with:
        python-version: ${{ env.Python_REQUIRED_VERSION }}
        architecture: ${{ matrix.arch }}

    - name: Create Build Directory
      run: cmake -E make_directory ./build/

    - name: Configure CMake
      working-directory: ./build
      shell: bash
      run: |
        set -x
        cmake -G "Visual Studio 16 2019" -A ${{ matrix.vs-generator }} \
              -DLINK_WITH_PYTHON:BOOL=ON -DPython_REQUIRED_VERSION:STRING=${{ steps.setup-python.outputs.python-version }} \
              -DPython_ROOT_DIR:PATH=$RUNNER_TOOL_CACHE/Python/${{ steps.setup-python.outputs.python-version }}/${{ matrix.arch }}/ \
              -DBUILD_FORTRAN:BOOL=ON \
              ../

    - name: Build Package
      working-directory: ./build
      shell: bash
      run: cmake --build . --target Basement_build -j 2 --config $BUILD_TYPE

    - name: Upload Basement
      uses: actions/upload-artifact@v2
      with:
        name: Basement
        path: build/Products/Basement.exe
